[package]
name = "capyctl-cli"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
serde_json = "1"
capyctl-domain = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
capyctl-agent = { workspace = true }
capyctl-config = { workspace = true }
capyctl-controller = { workspace = true }
capyctl-management = { path = "../capyctl-management" }
ulid = { workspace = true }
capyctl-store = { workspace = true }
capyctl-router = { path = "../capyctl-router" }
capyctl-adapters = { workspace = true }
capyctl-launchers = { path = "../capyctl-launchers" }
axum = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true, features = ["tls-ring"] }
tokio-stream = { version = "0.1", features = ["net"] }
capyctl-protocol = { workspace = true }
tempfile = { workspace = true }
libc = "0.2"
sha2 = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
clap-markdown = "=0.1.5"
capyctl-testkit = { workspace = true }
tempfile = { workspace = true }


[[bin]]
name = "capyctl"
path = "src/main.rs"
