[package]
name = "mllm-protocol"
edition.workspace = true
version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
mllm-domain = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }

serde_json = "1"
mllm-config.workspace = true

[dev-dependencies]
tokio = { workspace = true }
tokio-stream = "0.1"

[build-dependencies]
tonic-build = "0.13"
