[package]
name = "capyctl-store"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
capyctl-domain = { workspace = true }
capyctl-config = { workspace = true }
capyctl-scheduler = { workspace = true }
rusqlite = { workspace = true }
thiserror = { workspace = true }
ulid = { workspace = true }
serde = { workspace = true }
serde_json = { version = "1", features = ["raw_value"] }
sha2 = { workspace = true }
chacha20poly1305 = { version = "0.10", features = ["std"] }
rand_core = { version = "0.6", features = ["getrandom"] }
hex.workspace = true

[dev-dependencies]
tempfile = { workspace = true }
