[package]
name = "mllm-cli"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
mllm-agent = { workspace = true }
mllm-config = { workspace = true }
mllm-controller = { workspace = true }
mllm-store = { workspace = true }
mllm-router = { path = "../mllm-router" }
mllm-adapters = { workspace = true }
axum = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
serde_json = "1"
tempfile = { workspace = true }
mllm-domain = { workspace = true }


[[bin]]
name = "mllm"
path = "src/main.rs"