[package]
name = "mllm-store"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
mllm-domain = { workspace = true }
rusqlite = { workspace = true }
thiserror = { workspace = true }
ulid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
