[package]
name = "mllm-adapters"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
serde_json = "1"
mllm-config = { path = "../mllm-config" }
futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
axum = { workspace = true }
futures = { workspace = true }
[dev-dependencies.harness]
path = "../../tests/harness"
